# Generated by Django 3.1.2 on 2022-11-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mineralapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_the_mine', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_the_source', models.CharField(max_length=200)),
                ('url_link_to_the_source', models.CharField(max_length=200)),
                ('source_year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxesPaid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('name_of_the_mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineralapi.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='OreOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('name_of_the_mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineralapi.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='NetProfit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('name_of_the_mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineralapi.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='GrossRevenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('name_of_the_mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineralapi.mineral')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('parent_company_name', models.CharField(blank=True, max_length=100)),
                ('local_or_international', models.CharField(blank=True, max_length=100)),
                ('head_office_country', models.CharField(blank=True, max_length=100)),
                ('number_of_mines', models.PositiveIntegerField(blank=True)),
                ('average_percentage_of_CSR', models.ManyToManyField(blank=True, to='companyapi.CSR')),
                ('gross_revenue', models.ManyToManyField(blank=True, to='companyapi.GrossRevenue')),
                ('list_of_mines', models.ManyToManyField(blank=True, to='companyapi.Mine')),
                ('minerals_name', models.ManyToManyField(to='mineralapi.Mineral')),
                ('net_profit', models.ManyToManyField(blank=True, to='companyapi.NetProfit')),
                ('ore_Output', models.ManyToManyField(blank=True, to='companyapi.OreOutput')),
                ('sources', models.ManyToManyField(blank=True, to='companyapi.Source')),
                ('taxes_paid', models.ManyToManyField(blank=True, to='companyapi.TaxesPaid')),
            ],
        ),
    ]
