# Generated by Django 3.1.2 on 2022-11-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSR',
            new_name='CoperateSocialResponsibility',
        ),
    ]
