version: '3'
services:
  tmbackend:
    build: .
    image: mrmi-backend:latest
    ports:
      - "8009:8009"
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8009 &&
             gunicorn --bind=:8009 --workers=6 --threads=6 mrmiBackend.wsgi:application
             "
    volumes:
      - ./:/app
