# Generated by Django 3.1.2 on 2022-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineralapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='status',
        ),
        migrations.AddField(
            model_name='mineral',
            name='status',
            field=models.ManyToManyField(blank=True, to='mineralapi.Status'),
        ),
    ]
