# Generated by Django 3.1.2 on 2023-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('source_link', models.CharField(blank=True, default='', max_length=500)),
                ('report_files', models.FileField(blank=True, upload_to='mining-files')),
            ],
        ),
    ]
